# This is a basic workflow to help you get started with Actions

name: Deploy to github pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version:  14.x
          
      - name: Checkout branch
        uses: actions/checkout@v2
          
      - name: Clean install dependencies
        run: npm ci
        
    # Runs a set of commands using the runners shell
      - name: Run deploy script
        run: npm run gh-pages-deploy
